---
- name: check for flink installation...
  become: yes
  stat:
    path: '{{ flink_install_dir }}'
  changed_when: false
  register: flink_binary
- when: not flink_binary.stat.exists
  block:
    - name: download flink...
      become: yes
      become_user: root
      get_url:
        url: '{{ flink_url }}'
        dest: /tmp/{{ flink_archive }}
        mode: 0644
        checksum: '{{ flink_checksum }}'
        timeout: '{{ flink_download_timeout_seconds }}'
    - name: unarchive flink...
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ flink_archive }}
        dest: '{{ flink_install_parent_dir }}'
        creates: '{{ flink_install_dir }}'
  always:
    - name: delete archive
      become: yes
      become_user: root
      file:
        path: /tmp/{{ flink_archive }}
        state: absent

- name: link flink...
  become: yes
  become_user: root
  file:
    src: '{{ flink_install_dir }}'
    dest: '{{ flink_link_dir }}'
    state: link

- name: install flink into default path
  become: yes
  become_user: root
  with_items:
    - f: flink.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'
