---
- name: download flink...
  become: yes
  become_user: root
  get_url: >
    url={{flink_url}}
    dest=/tmp/{{flink_archive}}

- name: unarchive flink...
  become: yes
  become_user: root
  unarchive: >
    copy=no
    src=/tmp/{{flink_archive}}
    dest=/opt

- name: link flink...
  become: yes
  become_user: root
  file: >
    src=/opt/{{flink_name}}
    dest=/opt/flink
    state=link

- name: install flink into default path
  become: yes
  become_user: root
  copy: >
    src=etc/profile.d/flink.sh
    dest=/etc/profile.d/flink.sh
    mode=0644
